# https://github.com/volta-cli/volta/issues/1830#issuecomment-2615608641
enableGlobalCache: false
cacheFolder: './.yarn/cache'
cacheMigrationMode: 'always'
deferredVersionFolder: './.yarn/versions'
enableImmutableCache: false
